### ISSUE TITLE
Token Expiration Handling Causes Application Errors

### ISSUE THREAD

**Issue by ViezeVingertjes** [HeyM1ke/Assist#196]
The application encounters critical errors related to token expiration, which are not handled gracefully. This results in `BadRequest` errors during player data fetch operations due to failed token validation, and an `ArgumentNullException` in the application's internal operations. Notably, restarting Assist automatically logs the user back in, successfully retrieving a new token via another code path, which suggests that the issue could be circumvented with improved token handling.

### Console Log
```
[11:14:58 INF] Received Update Event to Update Values in Recent Matches List.
[11:14:58 INF] Refreshing Match Tracking Control.
[11:16:25 INF] Received User Presence Data
[11:16:25 ERR] Updating Data on Ingame
[11:16:26 FTL] Error on getting player coregame
[11:16:26 FTL] Error on getting player match or Pres
[11:16:26 FTL] COREGAME ERROR: BadRequest
[11:16:26 FTL] COREGAME ERROR: {"httpStatus": 400, "errorCode": "BAD_CLAIMS", "message": "Failure validating/decoding RSO Access Token"}
[11:16:26 INF] Token Expired Detected
```

### Stack Trace
```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Assist.Services.Modules.RichPresenceService.DisplayAgent(PlayerPresence pres) in C:\Repositories\Assist\Assist\Services\Modules\RichPresenceService.cs:line 406
   at Assist.Services.Modules.RichPresenceService.HandleSmallImageData(PlayerPresence pres) in C:\Repositories\Assist\Assist\Services\Modules\RichPresenceService.cs:line 307
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by HeyM1ke** [comment]
Hey! Thanks for the report. Issue has been fixed and will deploy on the next bug patch soon. 

Thank you! [Commit](https://github.com/HeyM1ke/Assist/commit/1d4a15adfb5a882c8d70e9d88c0a30fde169881c)
