### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by jrgmcl** [HeyM1ke/Assist#42]
Getting error after hitting login, I do think that it is because of the OTP that is required before logging in to riot or maybe something about permissions (?)

![image](https://user-images.githubusercontent.com/83060373/167244123-c52cad40-1245-4f3e-ad36-c2141de974a5.png)

**Comment by Ponita0** [comment]
Can you provide the log file?
Its in application data/assist/

**Comment by Xi2VAL** [comment]
Adding something as someone with the same issue, this is happening before I can see any other files beyond what I see her
![assistissue](https://user-images.githubusercontent.com/105254582/167521055-fef43500-a7ac-4634-8000-a3e33e8c6ca2.JPG)
e

**Comment by Xi2VAL** [comment]
I've gone into runtimes and theres nothing of note there just a folder trail to a .dll file

**Comment by HeyM1ke** [comment]
There is a message? on the side about error 403? Please read about that error.

**Comment by Xi2VAL** [comment]
i'm dumb hang on I got the log was checking the wrong place my b

[09/05/2022 20:54:31] : [NORMAL] Program Started
[09/05/2022 20:54:31] : [NORMAL] Created assist dirC:\Users\bwpea\AppData\Roaming\Assist
[09/05/2022 20:54:31] : [NORMAL] Trying to read settings
[09/05/2022 20:54:31] : [NORMAL] Read Settings
[09/05/2022 20:54:31] : [NORMAL] Changing Language
[5/9/2022 8:54:31 PM] : [NORMAL] Changed language to english
[5/9/2022 8:54:31 PM] : [NORMAL] Starting InitPage
[5/9/2022 8:54:32 PM] : [NORMAL] Checking for Assist Updates
[5/9/2022 8:54:32 PM] : [NORMAL] Starting Init Page
[5/9/2022 8:54:32 PM] : [NORMAL] InitPage Constructor Called
[5/9/2022 8:54:32 PM] : [NORMAL] Checking for Maintenance
[5/9/2022 8:54:32 PM] : [NORMAL] InitWindow_Loaded Called
[5/9/2022 8:54:32 PM] : [NORMAL] New User Flag is True, Running First Time Setup.
[5/9/2022 8:54:32 PM] : [NORMAL] Running First Time Setup
[5/9/2022 8:54:33 PM] : [NORMAL] Setting Settings RiotClient Path to Settings, Path Found: E:/Valorant/Riot Games/Riot Client/RiotClientServices.exe
[5/9/2022 8:54:49 PM] : [DEBUG] Found SSID Cookie from Authentication
[5/9/2022 8:54:49 PM] : [NORMAL] Authenticating with New User
[5/9/2022 8:54:49 PM] : [NORMAL] Authenticating with Cookies for New User
[5/9/2022 8:54:49 PM] : [ERROR] Unhandled Ex Source: Assist
[5/9/2022 8:54:49 PM] : [ERROR] Unhandled Ex StackTrace:    at Assist.MVVM.ViewModel.AssistAuthenticationController.CookieLogin(CookieContainer cc)
   at Assist.MVVM.View.Authentication.AuthenticationPages.RitoAuthentication.AuthUser()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[5/9/2022 8:54:49 PM] : [ERROR] Unhandled Ex Message: Sorry, you are not allowed to login. Error Code 403

**Comment by jrgmcl** [comment]
> Can you provide the log file? Its in application data/assist/

**Here:**
`[19/05/2022 8:05:48 pm] : [NORMAL] Program Started` </b>
`[19/05/2022 8:05:48 pm] : [NORMAL] Created assist dirC:\Users\jrgmcl\AppData\Roaming\Assist`</b>
`[19/05/2022 8:05:48 pm] : [NORMAL] Trying to read settings`</b>
`[19/05/2022 8:05:48 pm] : [NORMAL] Read Settings`</b>
`[19/05/2022 8:05:48 pm] : [NORMAL] Changing Language`</b>
`[5/19/2022 8:05:48 PM] : [NORMAL] Changed language to english`</b>
`[5/19/2022 8:05:48 PM] : [NORMAL] Starting InitPage`</b>
`[5/19/2022 8:05:48 PM] : [NORMAL] Checking for Assist Updates`</b>
`[5/19/2022 8:05:48 PM] : [NORMAL] Starting Init Page`</b>
`[5/19/2022 8:05:48 PM] : [NORMAL] InitPage Constructor Called`</b>
`[5/19/2022 8:05:49 PM] : [NORMAL] Checking for Maintenance`</b>
`[5/19/2022 8:05:50 PM] : [NORMAL] InitWindow_Loaded Called`</b>
`[5/19/2022 8:05:50 PM] : [NORMAL] New User Flag is True, Running First Time Setup.`</b>
`[5/19/2022 8:05:50 PM] : [NORMAL] Running First Time Setup`</b>
`[5/19/2022 8:05:50 PM] : [NORMAL] Setting Settings RiotClient Path to Settings, Path Found: D:/Riot Games/Riot Client/RiotClientServices.exe`</b>
`[5/19/2022 8:06:32 PM] : [DEBUG] Found SSID Cookie from Authentication`</b>
`[5/19/2022 8:06:32 PM] : [NORMAL] Authenticating with New User`</b>
`[5/19/2022 8:06:32 PM] : [NORMAL] Authenticating with Cookies for New User`</b>
`[5/19/2022 8:06:33 PM] : [ERROR] Unhandled Ex Source: Assist`</b>
`[5/19/2022 8:06:33 PM] : [ERROR] Unhandled Ex StackTrace:    at Assist.MVVM.ViewModel.AssistAuthenticationController.CookieLogin(CookieContainer cc)
   at Assist.MVVM.View.Authentication.AuthenticationPages.RitoAuthentication.AuthUser()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`</b>
`[5/19/2022 8:06:33 PM] : [ERROR] Unhandled Ex Message: Sorry, you are not allowed to login. Error Code 403`</b>

**Comment by HeyM1ke** [comment]
403 is a forbidden error. I recommend updating your windows, otherwise you are not able to use assist.
